//author AECL

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rpc-demo-gw.proto

package protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultCoords struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultCoords) Reset() {
	*x = MultCoords{}
	mi := &file_rpc_demo_gw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultCoords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultCoords) ProtoMessage() {}

func (x *MultCoords) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_demo_gw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultCoords.ProtoReflect.Descriptor instead.
func (*MultCoords) Descriptor() ([]byte, []int) {
	return file_rpc_demo_gw_proto_rawDescGZIP(), []int{0}
}

func (x *MultCoords) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_rpc_demo_gw_proto protoreflect.FileDescriptor

const file_rpc_demo_gw_proto_rawDesc = "" +
	"\n" +
	"\x11rpc-demo-gw.proto\x12\n" +
	"RPCDemoPkg\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"(\n" +
	"\n" +
	"MultCoords\x12\x1a\n" +
	"\x06values\x18\x01 \x03(\x01B\x02\x10\x01R\x06values2u\n" +
	"\aRPCDemo\x12j\n" +
	"\rGetMultCoords\x12\x16.google.protobuf.Empty\x1a\x16.RPCDemoPkg.MultCoords\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/restgatewaydemo/getmultcoordsB&Z$example.com/rest-gateway-demo/protosb\x06proto3"

var (
	file_rpc_demo_gw_proto_rawDescOnce sync.Once
	file_rpc_demo_gw_proto_rawDescData []byte
)

func file_rpc_demo_gw_proto_rawDescGZIP() []byte {
	file_rpc_demo_gw_proto_rawDescOnce.Do(func() {
		file_rpc_demo_gw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_demo_gw_proto_rawDesc), len(file_rpc_demo_gw_proto_rawDesc)))
	})
	return file_rpc_demo_gw_proto_rawDescData
}

var file_rpc_demo_gw_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rpc_demo_gw_proto_goTypes = []any{
	(*MultCoords)(nil),  // 0: RPCDemoPkg.MultCoords
	(*empty.Empty)(nil), // 1: google.protobuf.Empty
}
var file_rpc_demo_gw_proto_depIdxs = []int32{
	1, // 0: RPCDemoPkg.RPCDemo.GetMultCoords:input_type -> google.protobuf.Empty
	0, // 1: RPCDemoPkg.RPCDemo.GetMultCoords:output_type -> RPCDemoPkg.MultCoords
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_demo_gw_proto_init() }
func file_rpc_demo_gw_proto_init() {
	if File_rpc_demo_gw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_demo_gw_proto_rawDesc), len(file_rpc_demo_gw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_demo_gw_proto_goTypes,
		DependencyIndexes: file_rpc_demo_gw_proto_depIdxs,
		MessageInfos:      file_rpc_demo_gw_proto_msgTypes,
	}.Build()
	File_rpc_demo_gw_proto = out.File
	file_rpc_demo_gw_proto_goTypes = nil
	file_rpc_demo_gw_proto_depIdxs = nil
}
