name: Test Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  print-test:
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Print test message every 30 seconds
        run: |
          for n in {1..10}; do
            echo "test workflows #$n"

            if [ "$n" -lt 10 ]; then
              sleep 30
            fi
          done
